environment:
    nodejs_version: "Stable"

install:
    - ps: Install-Product node $env:nodejs_version
    - cmd: npm install npm@latest -g
    - cmd: npm install

build_script:
    cmd: echo ok

deploy_script:
    cmd: npm run semantic-release

on_failure:
    cmd: appveyor PushArtifact npm-debug.log